"""
refresh_enrichment_data.py — bake the current scraped data into 2_data.sql

    python refresh_enrichment_data.py                 # rewrite 2_data.sql in place
    python refresh_enrichment_data.py --check         # report only, change nothing
    python refresh_enrichment_data.py --out new.sql   # write elsewhere

Refreshes three blocks from the live database, in this order:

    job_listing      what the scrapers returned
    log_entry        the activity trail from those runs
    job_enrichment   the LLM extractions and embeddings for those listings

WHY ALL THREE, NOT JUST THE ENRICHMENT
======================================
`job_enrichment.job_listing_id` is a foreign key to `job_listing.id`, and
2_data.sql re-enables FOREIGN_KEY_CHECKS before any INSERT runs. Dumping the
enrichment alone would produce a file whose enrichment rows reference listings
the file does not contain — which restores fine on the machine it was dumped
from, because those listings are already there, and fails outright on a clean
install. That is the worst possible place to find out, so the three tables
that change together are written together.

`log_entry` is included because scraping writes to it: leaving it stale would
give a restored database listings with no record of the run that produced
them. It is dumped after the listings and before the enrichment so the file
stays in dependency order.

NOT dumped: `admin`, `provider_profile`, `scraper`, `schedule`. Those are
hand-maintained seed rows carrying the comments that explain why each exists —
why there is a "system" admin, why `limit_per_input` is capped at 10. A dump
would flatten them into positional tuples and lose every explanation. The
scraper rows also hold the BrightData key, which belongs in exactly one place.

WHY NOT JUST `mysqldump > 2_data.sql`
=====================================
Same reason. 2_data.sql is curated, not generated: it carries the DELETE block
that makes it safe to re-run and the commentary above each section. This
script replaces three delimited regions and leaves everything else alone.
Re-running it is safe — regions are matched by marker and replaced, never
appended twice.

WHAT IT NEEDS
=============
`mysqldump` on PATH, and the DB_* variables db.py already reads (from .env or
the environment). Use the copy that ships with your MySQL *Server*, not the
one bundled with Workbench — an older dump tool against a newer server can
emit SQL the server will not take back. On Windows the server binaries are at:

    C:\\Program Files\\MySQL\\MySQL Server <version>\\bin

Add that to PATH, or pass --mysqldump with the full path.

ORDER OF OPERATIONS
===================
Scrape, then `python enrich_jobs.py`, then this. A listing with no enrichment
row is invisible to matching, so dumping before enriching bakes in a database
that produces no matches. The script warns when it sees that.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile

from dotenv import load_dotenv

load_dotenv()

DATA_FILE = "2_data.sql"


class Block:
    """
    One generated region of 2_data.sql.

    `heading` is the comment introducing the section — originally the heading
    of the hand-written block this region replaces. The region starts there
    rather than at the BEGIN marker, so the first run absorbs the old heading
    instead of stranding it above the generated one.
    """

    def __init__(self, table, columns, heading, notes):
        self.table = table
        self.columns = columns
        self.heading = heading
        self.notes = notes
        self.begin = f"-- >>> BEGIN {table} (generated by refresh_enrichment_data.py) >>>"
        self.end = f"-- <<< END {table} <<<"

    def render(self, inserts):
        return (
            f"\n{self.heading}\n{self.notes.rstrip()}\n"
            f"{self.begin}\n{inserts}\n{self.end}\n"
        )


BLOCKS = [
    Block(
        "job_listing",
        ["id", "scraper_id", "url", "job_title", "company_name", "job_location",
         "job_details", "job_employment_type", "job_posted_date", "salary",
         "outdated_manual"],
        "-- Job listings ---------------------------------------------------------",
        """-- Everything the scrapers have returned, captured so a fresh install has
-- real data without anyone needing a BrightData key.
--
-- The seeded set was 20 listings from LinkedIn and Indeed, mostly
-- Thai-language, one of them deliberately more than 365 days old so the
-- SRS-029 outdated rule has something to filter. Keep at least one old
-- listing here when you regenerate, or that rule goes untested by the
-- sample data.""",
    ),
    Block(
        "log_entry",
        ["id", "user_id", "action", "target_name", "detail", "timestamp"],
        "-- Activity log ---------------------------------------------------------",
        """-- The trail from the scraper runs above. Regenerated alongside the
-- listings so a restored database does not show listings with no record of
-- the run that produced them.
--
-- user_id is a foreign key to admin.id, which is why the "system" account
-- exists: log_service falls back to it for anything with no signed-in
-- admin, such as an auto-run firing before login.""",
    ),
    Block(
        "job_enrichment",
        ["job_listing_id", "skills", "education", "education_requirement",
         "experience_years", "work_mode", "benefits", "embedding",
         "embedding_model", "embedding_dim", "enriched_at"],
        "-- Job enrichment --------------------------------------------------------",
        """-- The LLM extractions and embeddings for the listings above, captured
-- after a full `python enrich_jobs.py` run so a fresh install needs no
-- OpenAI calls to have working matches. This is the expensive part of the
-- file: one gpt-4o-mini call per listing to regenerate, plus a ~400 MB
-- model load for the vectors.
--
-- `embedding_model` travels with each vector on purpose: cosine similarity
-- between vectors from two different models is meaningless, so a restore
-- onto a machine running a different sentence-transformers release can be
-- detected instead of silently scoring wrong.""",
    ),
]


def _db_settings():
    return {
        "host": os.getenv("DB_HOST", "localhost"),
        "port": os.getenv("DB_PORT", "3306"),
        "user": os.getenv("DB_USER", "root"),
        "password": os.getenv("DB_PASSWORD", ""),
        "database": os.getenv("DB_NAME", "cvision"),
    }


def _resolve_mysqldump(mysqldump):
    if shutil.which(mysqldump) or os.path.isfile(mysqldump):
        return
    raise SystemExit(
        f"'{mysqldump}' not found. Add your MySQL Server bin directory to PATH,\n"
        "or pass the full path:\n"
        '  --mysqldump "C:\\Program Files\\MySQL\\MySQL Server 8.0\\bin\\mysqldump.exe"\n'
        "Find it with:\n"
        '  Get-ChildItem "C:\\Program Files" -Filter mysqldump.exe -Recurse '
        "-ErrorAction SilentlyContinue"
    )


def run_mysqldump(mysqldump, tables):
    """
    Dumps rows only — no CREATE TABLE, no mysqldump banner.

    One invocation for all three tables rather than three, so every block
    comes from a single --single-transaction snapshot. Dumping separately
    would let a scraper run land between calls and produce a file whose
    enrichment references a listing the listing block does not have.

    The password goes through a temporary defaults file rather than
    --password= on the command line, which would be visible to anyone running
    `ps` and makes mysqldump print a warning about exactly that.
    """
    cfg = _db_settings()
    fd, defaults_path = tempfile.mkstemp(suffix=".cnf", text=True)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(
                "[client]\n"
                f"host={cfg['host']}\n"
                f"port={cfg['port']}\n"
                f"user={cfg['user']}\n"
                f"password={cfg['password']}\n"
            )
        result = subprocess.run(
            [
                mysqldump,
                f"--defaults-extra-file={defaults_path}",
                "--no-create-info",
                "--skip-comments",
                "--single-transaction",
                "--complete-insert",
                "--default-character-set=utf8mb4",
                cfg["database"],
                *tables,
            ],
            capture_output=True,
            text=True,
            encoding="utf-8",
        )
    finally:
        os.unlink(defaults_path)

    if result.returncode != 0:
        raise SystemExit(f"mysqldump failed:\n{(result.stderr or '').strip()}")
    return result.stdout


def split_by_table(dump):
    """
    Groups the dump's INSERT statements by table name.

    mysqldump's session-variable scaffolding is dropped — 2_data.sql sets and
    restores those things itself.
    """
    grouped = {}
    for statement in re.findall(r"^INSERT INTO .*?;\s*$", dump,
                                flags=re.MULTILINE | re.DOTALL):
        table = re.search(r"INSERT INTO `([^`]+)`", statement).group(1)
        grouped.setdefault(table, []).append(statement.rstrip())
    return grouped


def check_columns(block, statements):
    """
    Confirms the live table matches 1_structure.sql before anything is written.

    --complete-insert names the columns in every statement, so this catches a
    schema drift here rather than on someone else's restore. The specific case
    it was written for: a database created before `translated_description` was
    dropped still has that column, and a dump carrying it restores cleanly on
    the machine it came from and fails everywhere else.
    """
    for statement in statements:
        header = statement[: statement.index("VALUES")]
        columns = re.findall(r"`([^`]+)`", header)[1:]  # first backtick is the table
        if columns != block.columns:
            unexpected = [c for c in columns if c not in block.columns]
            missing = [c for c in block.columns if c not in columns]
            raise SystemExit(
                f"`{block.table}` does not match 1_structure.sql — nothing written.\n"
                f"  unexpected columns: {unexpected or 'none'}\n"
                f"  missing columns:    {missing or 'none'}\n"
                "Run drop_translated_description.sql, or rebuild from "
                "1_structure.sql, then enrich again."
            )


def count_rows(statements):
    return sum(s.count("),(") + 1 for s in statements)


def splice(existing, block, rendered):
    """
    Replaces the block's region if present, appends it if not.

    Three cases: the region has been generated before (markers present), the
    hand-written section is still there (heading present, no markers), or
    neither, in which case the block is appended at the end of the file.
    """
    if block.begin in existing:
        start = (existing.index(block.heading) if block.heading in existing
                 else existing.index(block.begin))
        end = existing.index(block.end) + len(block.end)
    elif block.heading in existing:
        # First run: swallow the hand-written section, up to the next heading.
        start = existing.index(block.heading)
        after = start + len(block.heading)
        following = [existing.index(other.heading, after)
                     for other in BLOCKS
                     if other is not block and other.heading in existing[after:]]
        end = min(following) if following else len(existing)
    else:
        return existing.rstrip("\n") + "\n" + rendered

    tail = existing[end:].lstrip("\n")
    return (existing[:start].rstrip("\n") + "\n"
            + rendered.lstrip("\n")
            + ("\n" + tail if tail.strip() else ""))


def main():
    parser = argparse.ArgumentParser(
        description="Bake the current scraped data and enrichment into 2_data.sql."
    )
    parser.add_argument("--check", action="store_true",
                        help="report what would change and exit")
    parser.add_argument("--out", default=DATA_FILE,
                        help=f"file to write (default: {DATA_FILE})")
    parser.add_argument("--data-file", default=DATA_FILE,
                        help=f"file to read (default: {DATA_FILE})")
    parser.add_argument("--mysqldump", default="mysqldump",
                        help="path to mysqldump if it is not on PATH")
    args = parser.parse_args()

    if not os.path.isfile(args.data_file):
        raise SystemExit(f"{args.data_file} not found. Run this from the project root.")

    _resolve_mysqldump(args.mysqldump)
    cfg = _db_settings()
    print(f"Dumping {', '.join(b.table for b in BLOCKS)} from {cfg['database']}...")

    grouped = split_by_table(run_mysqldump(args.mysqldump, [b.table for b in BLOCKS]))

    counts, rendered = {}, {}
    for block in BLOCKS:
        statements = grouped.get(block.table, [])
        check_columns(block, statements)
        counts[block.table] = count_rows(statements)
        rendered[block.table] = block.render("\n".join(statements))
        print(f"  {block.table:<16} {counts[block.table]:>5} rows")

    if counts["job_listing"] == 0:
        raise SystemExit("No job listings found — there is nothing to bake in.")

    # The failure this script exists to prevent, checked directly rather than
    # trusted to the ordering above.
    if counts["job_enrichment"] > counts["job_listing"]:
        raise SystemExit(
            "More enrichment rows than listings — a restore would hit a foreign "
            "key error. Something is out of step; nothing written."
        )
    if counts["job_enrichment"] < counts["job_listing"]:
        gap = counts["job_listing"] - counts["job_enrichment"]
        print(f"\n  WARNING: {gap} listing(s) have no enrichment row and will be")
        print("           invisible to matching. Run `python enrich_jobs.py` first")
        print("           unless you meant to ship them un-enriched.")

    existing = open(args.data_file, encoding="utf-8").read()
    updated = existing
    for block in BLOCKS:
        updated = splice(updated, block, rendered[block.table])

    if args.check:
        print(f"\n  {args.data_file} would go from {len(existing):,} to "
              f"{len(updated):,} bytes. Nothing written (--check).")
        return

    if args.out == args.data_file:
        backup = args.data_file + ".bak"
        shutil.copyfile(args.data_file, backup)
        print(f"\n  previous version saved as {backup}")

    with open(args.out, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(updated)
    print(f"  wrote {args.out} ({len(updated):,} bytes)")

    print("\nRestore now needs no OpenAI calls. Prove it on a clean rebuild:")
    print("  mysqlsh --sql -u root -p -h localhost --file 1_structure.sql")
    print(f"  mysqlsh --sql -u root -p -h localhost --file {args.out}")
    print("  python verify_integration.py --no-ai")


if __name__ == "__main__":
    sys.exit(main())